### PR TITLE
Instructions ready to be reviewed

### PR DESCRIPTION
**Pull request by vivigirardin**
Let me know if this is good or what needs to be changed/improved: 
https://nivanorge.github.io/instructions-dmp-argos/

### CODE REVIEW

**Review by knl88 — APPROVED** [review]
Think it looks good, perhaps we should include instructions on adding new datasets, for example if the given task produces more than one dataset?

**Comment by vivigirardin** [comment]
> Think it looks good, perhaps we should include instructions on adding new datasets, for example if the given task produces more than one dataset?

Only owners can add new datasets. How do you want to manage that @knl88 ?

**Comment by knl88** [comment]
Can we add more owners? Perhaps we just create them then, preferably from zenodo datasets

**Comment by vivigirardin** [comment]
> Can we add more owners? Perhaps we just create them then, preferably from zenodo datasets

@knl88 , only you can add owners ( you are the only owner at the moment). I think it is best that the author adds the dataset to Zenodo and we create them as you are suggesting.

**Pull request merged**
